package com.quattrinh.shop.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductAttributeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAttributeAllPropertiesEquals(ProductAttribute expected, ProductAttribute actual) {
        assertProductAttributeAutoGeneratedPropertiesEquals(expected, actual);
        assertProductAttributeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAttributeAllUpdatablePropertiesEquals(ProductAttribute expected, ProductAttribute actual) {
        assertProductAttributeUpdatableFieldsEquals(expected, actual);
        assertProductAttributeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAttributeAutoGeneratedPropertiesEquals(ProductAttribute expected, ProductAttribute actual) {
        assertThat(expected)
            .as("Verify ProductAttribute auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAttributeUpdatableFieldsEquals(ProductAttribute expected, ProductAttribute actual) {
        assertThat(expected)
            .as("Verify ProductAttribute relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductAttributeUpdatableRelationshipsEquals(ProductAttribute expected, ProductAttribute actual) {
        // empty method
    }
}
