package com.quattrinh.shop.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VariantAttributeValueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariantAttributeValueAllPropertiesEquals(VariantAttributeValue expected, VariantAttributeValue actual) {
        assertVariantAttributeValueAutoGeneratedPropertiesEquals(expected, actual);
        assertVariantAttributeValueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariantAttributeValueAllUpdatablePropertiesEquals(
        VariantAttributeValue expected,
        VariantAttributeValue actual
    ) {
        assertVariantAttributeValueUpdatableFieldsEquals(expected, actual);
        assertVariantAttributeValueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariantAttributeValueAutoGeneratedPropertiesEquals(
        VariantAttributeValue expected,
        VariantAttributeValue actual
    ) {
        assertThat(expected)
            .as("Verify VariantAttributeValue auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariantAttributeValueUpdatableFieldsEquals(VariantAttributeValue expected, VariantAttributeValue actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVariantAttributeValueUpdatableRelationshipsEquals(
        VariantAttributeValue expected,
        VariantAttributeValue actual
    ) {
        assertThat(expected)
            .as("Verify VariantAttributeValue relationships")
            .satisfies(e -> assertThat(e.getVariant()).as("check variant").isEqualTo(actual.getVariant()))
            .satisfies(e -> assertThat(e.getAttributeValue()).as("check attributeValue").isEqualTo(actual.getAttributeValue()));
    }
}
